language: go
go:
  - 1.12.x
script:
  - make deps
  - make test
  - make build-travis
sudo: false
deploy:
  provider: releases
  api_key:
    secure: OYTe/y59Fai/XvLZIIydrHxLPSUZDm2Ocw1MVLEFf5r7p/wcxw4V5KWI4+A4LkXBNK4TguXLc4uKeLKSoXJ/l3z57cT5w6zbTBxdWJ+hjphamyIV5WDE7jx7tpW3TO4s6ZlD+hpYc2vF4bVme1K1DQvkIDBQFMvCxHOMMp2noHC8zxQ3ZUC4pA2WkBOEenUEXexhoiVnk14OmlyIclVhdgIvr5zypiIAtquc0mlQ7WJKkCScwHGB9cM20GUI7/gWv40Nrhm5FfSxl61BkU0fIArLNRh8LyDLgZkCeN9S2m5LV+OQEDEM8Bvdd+FHkrhiASUTyTuAApllXB868gjH/7bK1913jajx79hsRS1mky4BsP4l9Xf2OJSy6cv3AbQmoDhcB51vgbcOjUm93RBf6wx3Xj0c0m4bl2bPrT0L0TBCQZb/r0XHfIbtORJWKUoItoTY1TqKzvzYLLhtHwgMkgMbPb0q43m/C6DkCqdSz8bi1fzV36RuhoIhyrS6AV9h9S67m1yrgVYcabPpYUsllQAbjfcbXD41X80+oylQqjKthiFz0fEsYvEDTKYixTeeRqICGkJT5LszpnHL6rBIPuHJp5rZJYktCK3YMkmrM2l+vqZVvgQMWK1H9KXxzORshjR8/sFHn5+O1q4U+9XTAfW1OtY0inMwvrOaM8XppGU=
  file: http-proxy-tester
  skip_cleanup: true
  draft: true
  on:
    repo: criteo/http-proxy-tester
    tags: true
