language: go
go:
  - 1.12.x
script:
  - make deps
  - make test
  - make build-travis
sudo: false
deploy:
  provider: releases
  api_key:
    secure: j1FFz3p4jM0W8l3Snr/O5pNrqPvEUjxKFIfstXGGepD20hN2WxSo0a9LC3JEyEtxA8BwfM7388T0+4oKvffwnKB1hupxguHM/w9I6DaMqv9xWltqK/R5aQoKd/hBmhNAt8zgc2FU5iW0QwtjadNvyHpb1RNX/eWbM21r0Tlu+jcb6a7pXZloVgH8qQdBnoslDsER3Of7mugpBQMtKIY7pyCabxAPqmvB5O9pcGkqO7azwn4K87Gg+py9BV1Ev9lCLe1AUzA8WeVdXy86MshkBI1AvVRK2J7en/irbHHtad2FW4kYXKHPA7Gb/bw0OLKn0DCVnq8oMtLgn0vaVhWhDx3W8WwooiGqNAoyQv916lmT9zd9As0ya9fUL82b6F7UTFYKIxZMVIEfYuIqxfkw6LZx6yQgOAoL43Q8Tx/KnbsW28Oymf1TA/TILKp/6u6datVVsblZCzGK8hrfVdpkusuBmQMHZUGcrJL+A0S4jb7rvZ8MnKSRnXfzhkYc19KyrjhN8/t7dqn/jDyvOD3Vi/yfX+acCvsjwLw17HBSfFCihqpzGt+7XR71cM7fDQY8TgURXkjCg/8hbFkwp0owUHn3iREAKs0Rge91nuC5dJ2ACR1UL9zmY00rLx4kgV6+kXfXhQKogSg7NuScAyLgjVkUdAYM2w1AlYcnbzpRpJo=
  file: http-proxy-tester
  skip_cleanup: true
  draft: true
  on:
    repo: criteo/http-proxy-tester
    tags: true
